services:
  pokemon-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      TOKEN_EXPIRY_MINUTES: "${TOKEN_EXPIRY_MINUTES}"