services:
  pokemon-api:
    build: .
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5000/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      TOKEN_EXPIRY_MINUTES: "${TOKEN_EXPIRY_MINUTES}"