# Simple in-memory data for Pokémon
pokemon_data = [
    {"name": "Bulbasaur", "type": ["grass", "poison"]},
    {"name": "Ivysaur", "type": ["grass", "poison"]},
    {"name": "Venusaur", "type": ["grass", "poison"]},
    {"name": "Charmander", "type": "fire"},
    {"name": "Charmeleon", "type": "fire"},
    {"name": "Charizard", "type": ["fire", "flying"]},
    {"name": "Squirtle", "type": "water"},
    {"name": "Wartortle", "type": "water"},
    {"name": "Blastoise", "type": "water"},
    {"name": "Caterpie", "type": "bug"},
    {"name": "Metapod", "type": "bug"},
    {"name": "Butterfree", "type": ["bug", "flying"]},
    {"name": "Weedle", "type": ["bug", "poison"]},
    {"name": "Kakuna", "type": ["bug", "poison"]},
    {"name": "Beedrill", "type": ["bug", "poison"]},
    {"name": "Pidgey", "type": ["normal", "flying"]},
    {"name": "Pidgeotto", "type": ["normal", "flying"]},
    {"name": "Pidgeot", "type": ["normal", "flying"]},
    {"name": "Rattata", "type": "normal"},
    {"name": "Raticate", "type": "normal"},
    {"name": "Spearow", "type": ["normal", "flying"]},
    {"name": "Fearow", "type": ["normal", "flying"]},
    {"name": "Ekans", "type": "poison"},
    {"name": "Arbok", "type": "poison"},
    {"name": "Pikachu", "type": "electric"},
    {"name": "Raichu", "type": "electric"},
    {"name": "Sandshrew", "type": "ground"},
    {"name": "Sandslash", "type": "ground"},
    {"name": "Nidoran♀", "type": "poison"},
    {"name": "Nidorina", "type": "poison"},
    {"name": "Nidoqueen", "type": ["poison", "ground"]},
    {"name": "Nidoran♂", "type": "poison"},
    {"name": "Nidorino", "type": "poison"},
    {"name": "Nidoking", "type": ["poison", "ground"]},
    {"name": "Clefairy", "type": "fairy"},
    {"name": "Clefable", "type": "fairy"},
    {"name": "Vulpix", "type": "fire"},
    {"name": "Ninetales", "type": "fire"},
    {"name": "Jigglypuff", "type": ["normal", "fairy"]},
    {"name": "Wigglytuff", "type": ["normal", "fairy"]},
    {"name": "Zubat", "type": ["poison", "flying"]},
    {"name": "Golbat", "type": ["poison", "flying"]},
    {"name": "Oddish", "type": ["grass", "poison"]},
    {"name": "Gloom", "type": ["grass", "poison"]},
    {"name": "Vileplume", "type": ["grass", "poison"]},
    {"name": "Paras", "type": ["bug", "grass"]},
    {"name": "Parasect", "type": ["bug", "grass"]},
    {"name": "Venonat", "type": ["bug", "poison"]},
    {"name": "Venomoth", "type": ["bug", "poison"]},
    {"name": "Diglett", "type": "ground"},
    {"name": "Dugtrio", "type": "ground"},
    {"name": "Meowth", "type": "normal"},
    {"name": "Persian", "type": "normal"},
    {"name": "Psyduck", "type": "water"},
    {"name": "Golduck", "type": "water"},
    {"name": "Mankey", "type": "fighting"},
    {"name": "Primeape", "type": "fighting"},
    {"name": "Growlithe", "type": "fire"},
    {"name": "Arcanine", "type": "fire"},
    {"name": "Poliwag", "type": "water"},
    {"name": "Poliwhirl", "type": "water"},
    {"name": "Poliwrath", "type": ["water", "fighting"]},
    {"name": "Abra", "type": "psychic"},
    {"name": "Kadabra", "type": "psychic"},
    {"name": "Alakazam", "type": "psychic"},
    {"name": "Machop", "type": "fighting"},
    {"name": "Machoke", "type": "fighting"},
    {"name": "Machamp", "type": "fighting"},
    {"name": "Bellsprout", "type": ["grass", "poison"]},
    {"name": "Weepinbell", "type": ["grass", "poison"]},
    {"name": "Victreebel", "type": ["grass", "poison"]},
    {"name": "Tentacool", "type": ["water", "poison"]},
    {"name": "Tentacruel", "type": ["water", "poison"]},
    {"name": "Geodude", "type": ["rock", "ground"]},
    {"name": "Graveler", "type": ["rock", "ground"]},
    {"name": "Golem", "type": ["rock", "ground"]},
    {"name": "Ponyta", "type": "fire"},
    {"name": "Rapidash", "type": "fire"},
    {"name": "Slowpoke", "type": ["water", "psychic"]},
    {"name": "Slowbro", "type": ["water", "psychic"]},
    {"name": "Magnemite", "type": ["electric", "steel"]},
    {"name": "Magneton", "type": ["electric", "steel"]},
    {"name": "Farfetch'd", "type": ["normal", "flying"]},
    {"name": "Doduo", "type": ["normal", "flying"]},
    {"name": "Dodrio", "type": ["normal", "flying"]},
    {"name": "Seel", "type": "water"},
    {"name": "Dewgong", "type": ["water", "ice"]},
    {"name": "Grimer", "type": "poison"},
    {"name": "Muk", "type": "poison"},
    {"name": "Shellder", "type": "water"},
    {"name": "Cloyster", "type": ["water", "ice"]},
    {"name": "Gastly", "type": ["ghost", "poison"]},
    {"name": "Haunter", "type": ["ghost", "poison"]},
    {"name": "Gengar", "type": ["ghost", "poison"]},
    {"name": "Onix", "type": ["rock", "ground"]},
    {"name": "Drowzee", "type": "psychic"},
    {"name": "Hypno", "type": "psychic"},
    {"name": "Krabby", "type": "water"},
    {"name": "Kingler", "type": "water"},
    {"name": "Voltorb", "type": "electric"},
    {"name": "Electrode", "type": "electric"},
    {"name": "Exeggcute", "type": ["grass", "psychic"]},
    {"name": "Exeggutor", "type": ["grass", "psychic"]},
    {"name": "Cubone", "type": "ground"},
    {"name": "Marowak", "type": "ground"},
    {"name": "Hitmonlee", "type": "fighting"},
    {"name": "Hitmonchan", "type": "fighting"},
    {"name": "Lickitung", "type": "normal"},
    {"name": "Koffing", "type": "poison"},
    {"name": "Weezing", "type": "poison"},
    {"name": "Rhyhorn", "type": ["ground", "rock"]},
    {"name": "Rhydon", "type": ["ground", "rock"]},
    {"name": "Chansey", "type": "normal"},
    {"name": "Tangela", "type": "grass"},
    {"name": "Kangaskhan", "type": "normal"},
    {"name": "Horsea", "type": "water"},
    {"name": "Seadra", "type": "water"},
    {"name": "Goldeen", "type": "water"},
    {"name": "Seaking", "type": "water"},
    {"name": "Staryu", "type": "water"},
    {"name": "Starmie", "type": ["water", "psychic"]},
    {"name": "Mr. Mime", "type": ["psychic", "fairy"]},
    {"name": "Scyther", "type": ["bug", "flying"]},
    {"name": "Jynx", "type": ["ice", "psychic"]},
    {"name": "Electabuzz", "type": "electric"},
    {"name": "Magmar", "type": "fire"},
    {"name": "Pinsir", "type": "bug"},
    {"name": "Tauros", "type": "normal"},
    {"name": "Magikarp", "type": "water"},
    {"name": "Gyarados", "type": ["water", "flying"]},
    {"name": "Lapras", "type": ["water", "ice"]},
    {"name": "Ditto", "type": "normal"},
    {"name": "Eevee", "type": "normal"},
    {"name": "Vaporeon", "type": "water"},
    {"name": "Jolteon", "type": "electric"},
    {"name": "Flareon", "type": "fire"},
    {"name": "Porygon", "type": "normal"},
    {"name": "Omanyte", "type": ["rock", "water"]},
    {"name": "Omastar", "type": ["rock", "water"]},
    {"name": "Kabuto", "type": ["rock", "water"]},
    {"name": "Kabutops", "type": ["rock", "water"]},
    {"name": "Aerodactyl", "type": ["rock", "flying"]},
    {"name": "Snorlax", "type": "normal"},
    {"name": "Articuno", "type": ["ice", "flying"]},
    {"name": "Zapdos", "type": ["electric", "flying"]},
    {"name": "Moltres", "type": ["fire", "flying"]},
    {"name": "Dratini", "type": "dragon"},
    {"name": "Dragonair", "type": "dragon"},
    {"name": "Dragonite", "type": ["dragon", "flying"]},
    {"name": "Mewtwo", "type": "psychic"},
    {"name": "Mew", "type": "psychic"}
]